version: '3.5'

services:
  rabbit:
    container_name: dva_rabbit
    networks:
      - dvadev_default
    build:
      context: .
      dockerfile: ./rabbit.Dockerfile
    image: dva_rabbit
    ports:
      # - "15671:15671"
      - "15672:15672"
      - "5672:5672"

  db:
    container_name: dva_db
    networks:
      - dvadev_default
    build:
      context: ./db/
      dockerfile: db.Dockerfile
    image: dva_db
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

  coinbase_worker:
    container_name: dva_coinbase_worker
    networks:
      - dvadev_default
    depends_on:
      - rabbit
    build:
      context: ./worker/coinbase/
      dockerfile: coinbase.Dockerfile
    image: dva_worker
    ports:
      # HTTP Port
      - 8081:8080

  gemini_worker:
    container_name: dva_gemini_worker
    networks:
      - dvadev_default
    depends_on:
      - rabbit
    build:
      context: ./worker/gemini/
      dockerfile: gemini.Dockerfile
    image: dva_worker
    ports:
      # HTTP Port
      - 8080:8080

  postgres_saver:
    container_name: dva_postgres_saver
    networks:
      - dvadev_default
    depends_on:
      # - db
      - rabbit
    build:
      context: ./saver/postgres/
      dockerfile: Dockerfile
    image: dva_postgres_saver

  prometheus:
    container_name: dva_prom
    image: dva_prometheus
    networks:
      - dvadev_default
    build:
      context: .
      dockerfile: prom.Dockerfile
    depends_on:
      - rabbit
    ports:
      - 9090:9090
    volumes:
      - ./prom:/etc/prometheus

networks:
  dvadev_default:
    external:
      name: dvadev_default



  # bigquery:
  #   container_name: dva_bigquery_saver
  #   networks:
  #     - dvadev_default
  #   # depends_on:
  #   #   - rabbit
  #   build:
  #     context: ./saver/bigquery/
  #     dockerfile: Dockerfile
  #   image: dva_bigquery_saver
  #   restart: always
  #   ports:
  #       - 80:80