apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: coinbase_dva_worker
    context: worker/coinbase
    docker:
      dockerfile: worker.Dockerfile
  - image: dva_prometheus
    docker:
      dockerfile: prom.Dockerfile
  - image: dva_rabbit
    docker:
      dockerfile: rabbit.Dockerfile
  - image: dva_db
    context: db/
    docker:
      dockerfile: db.Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployments/coinbase.worker.yaml
    - k8s/deployments/prometheus.yaml
    - k8s/deployments/rabbit.yaml
    - k8s/deployments/postgres.yaml
