apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    app: worker
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: coinbase_dva_worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http