apiVersion: v1
kind: Service
metadata:
  name: prom
  labels:
    app: prom
spec:
  selector:
    app: prom
  type: LoadBalancer
  ports:
    - port: 9090
      name: prom
      protocol: TCP
      targetPort: 9090
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: prom
          imagePullPolicy: Never
          image: dva_prometheus
          ports:
            - name: prom
              containerPort: 9090
