apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app: api
spec:
  selector:
    app: rabbit
  type: LoadBalancer
  ports:
    - port: 15672
      name: rabbit-ui
      protocol: TCP
      targetPort: 15672
    - port: 15671
      name: rabbit-ui-2
      protocol: TCP
      targetPort: 15671
    - port: 5672
      name: rabbit
      protocol: TCP
      targetPort: 5672
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  selector:
    matchLabels:
      app: rabbit # has to match .spec.template.metadata.labels
  serviceName: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          imagePullPolicy: Never
          image: dva_rabbit
          ports:
            - name: rabbit-ui
              containerPort: 15672
            - name: rabbit-ui-2
              containerPort: 15671
            - name: rabbit
              containerPort: 5672